libdigidocpp: digidoc::DigiDocConf Class Reference
digidoc::DigiDocConf Class Reference
#include <libdigidocpp.i.h>
Inherits digidoc::XmlConfV3.
Public Member Functions
DigiDocConf (std::string _cache)
int logLevel () const override
std::string logFile () const override
std::string ocsp (const std::string &issuer) const override
std::string PKCS12Cert () const override
std::set< std::string > OCSPTMProfiles () const override
std::string TSLCache () const override
std::vector< X509Cert > TSLCerts () const override
std::string TSLUrl () const override
X509Cert verifyServiceCert () const override
std::string verifyServiceUri () const override
std::string xsdPath () const override
void setTSLCert (const std::vector< unsigned char > &cert)
void addTSLCert (const std::vector< unsigned char > &cert)
void setTSLUrl (std::string url)
void setOCSPUrls (std::map< std::string, std::string > urls)
void setOCSPTMProfiles (const std::vector< std::string > &_TMProfiles)
void setVerifyServiceCert (const std::vector< unsigned char > &cert)
void setVerifyServiceUri (std::string url)
Public Member Functions inherited from digidoc::XmlConfV3
XmlConfV3 (const std::string &path={}, const std::string &schema={})
~XmlConfV3 () override
int logLevel () const override
std::string logFile () const override
std::string PKCS11Driver () const override
std::string proxyHost () const override
std::string proxyPort () const override
std::string proxyUser () const override
std::string proxyPass () const override
bool proxyForceSSL () const override
bool proxyTunnelSSL () const override
std::string digestUri () const override
std::string signatureDigestUri () const override
std::string ocsp (const std::string &issuer) const override
std::set< std::string > OCSPTMProfiles () const override
std::string TSUrl () const override
X509Cert verifyServiceCert () const override
std::string verifyServiceUri () const override
std::string PKCS12Cert () const override
std::string PKCS12Pass () const override
bool PKCS12Disable () const override
bool TSLAutoUpdate () const override
std::string TSLCache () const override
bool TSLOnlineDigest () const override
int TSLTimeOut () const override
virtual void setProxyHost (const std::string &host)
virtual void setProxyPort (const std::string &port)
virtual void setProxyUser (const std::string &user)
virtual void setProxyPass (const std::string &pass)
virtual void setProxyTunnelSSL (bool enable)
virtual void setPKCS12Cert (const std::string &cert)
virtual void setPKCS12Pass (const std::string &pass)
virtual void setPKCS12Disable (bool disable)
virtual void setTSLOnlineDigest (bool enable)
virtual void setTSLTimeOut (int timeOut)
virtual void setTSUrl (const std::string &url)
Public Member Functions inherited from digidoc::ConfV3
ConfV3 ()
~ConfV3 () override
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
~ConfV2 () override
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual DIGIDOCPP_DEPRECATED std::string libdigidocConf () const
virtual DIGIDOCPP_DEPRECATED std::string certsPath () const
virtual bool TSLAllowExpired () const
Static Public Member Functions
static DigiDocConf * instance ()
Static Public Member Functions inherited from digidoc::XmlConfV3
static XmlConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV3
static ConfV3 * instance ()
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Constructor & Destructor Documentation
DigiDocConf()
digidoc::DigiDocConf::DigiDocConf (std::string _cache) inline
Member Function Documentation
addTSLCert()
void digidoc::DigiDocConf::addTSLCert (const std::vector< unsigned char > & cert) inline
References digidoc::X509Cert::Der.
instance()
static DigiDocConf* digidoc::DigiDocConf::instance () inline static
References digidoc::Conf::instance().
logFile()
std::string digidoc::DigiDocConf::logFile () const inline override virtual
Gets log file location. Default log goes to standard out stream
Reimplemented from digidoc::Conf.
References digidoc::XmlConfV3::logFile().
logLevel()
int digidoc::DigiDocConf::logLevel () const inline override virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented from digidoc::Conf.
ocsp()
std::string digidoc::DigiDocConf::ocsp (const std::string & issuer) const inline override virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented from digidoc::Conf.
OCSPTMProfiles()
std::set<std::string> digidoc::DigiDocConf::OCSPTMProfiles () const inline override virtual
Gets verify service Cert
Reimplemented from digidoc::ConfV3.
References digidoc::XmlConfV3::OCSPTMProfiles().
PKCS12Cert()
std::string digidoc::DigiDocConf::PKCS12Cert () const inline override virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented from digidoc::Conf.
References digidoc::XmlConfV3::PKCS12Cert().
setOCSPTMProfiles()
void digidoc::DigiDocConf::setOCSPTMProfiles (const std::vector< std::string > & _TMProfiles) inline
setOCSPUrls()
void digidoc::DigiDocConf::setOCSPUrls (std::map< std::string, std::string > urls) inline
setTSLCert()
void digidoc::DigiDocConf::setTSLCert (const std::vector< unsigned char > & cert) inline
References digidoc::X509Cert::Der.
setTSLUrl()
void digidoc::DigiDocConf::setTSLUrl (std::string url) inline
setVerifyServiceCert()
void digidoc::DigiDocConf::setVerifyServiceCert (const std::vector< unsigned char > & cert) inline
References digidoc::X509Cert::Der.
setVerifyServiceUri()
void digidoc::DigiDocConf::setVerifyServiceUri (std::string url) inline
TSLCache()
std::string digidoc::DigiDocConf::TSLCache () const inline override virtual
TSL cache path in local file system
Reimplemented from digidoc::Conf.
References digidoc::XmlConfV3::TSLCache().
TSLCerts()
std::vector<X509Cert> digidoc::DigiDocConf::TSLCerts () const inline override virtual
TSL master list's (LOTL) signing certificates
Reimplemented from digidoc::Conf.
References digidoc::Conf::TSLCerts().
TSLUrl()
std::string digidoc::DigiDocConf::TSLUrl () const inline override virtual
TSL master list's (LOTL) URL
Reimplemented from digidoc::Conf.
References digidoc::Conf::TSLUrl().
verifyServiceCert()
X509Cert digidoc::DigiDocConf::verifyServiceCert () const inline override virtual
Gets verify service Cert
Reimplemented from digidoc::ConfV2.
References digidoc::XmlConfV3::verifyServiceCert().
verifyServiceUri()
std::string digidoc::DigiDocConf::verifyServiceUri () const inline override virtual
Gets verify service URI
Reimplemented from digidoc::Conf.
References digidoc::XmlConfV3::verifyServiceUri().
xsdPath()
std::string digidoc::DigiDocConf::xsdPath () const inline override virtual
Gets XSD schema files path
Reimplemented from digidoc::Conf.
References digidoc::Conf::xsdPath().
The documentation for this class was generated from the following file:
libdigidocpp.i.h